### ISSUE TITLE
Masih ada tulisan template

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#1]
Masih ada tulisan template dari colorlib pada title dari file index.php
![bug 1](https://user-images.githubusercontent.com/53895082/66936756-6dbeda00-f068-11e9-83cc-12f25e231040.png)

**Comment by belladewusa** [comment]
![Screenshot (110)](https://user-images.githubusercontent.com/55181780/67279098-87db3b00-f4f4-11e9-8dfd-35568dbacdfc.png)
