### ISSUE TITLE
Password dalam bentuk plaintext

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#10]
Pada bagian database seharusnya password dalam bentuk hash dan bukan dalam bentuk plaintext karena sangat rawan. Jika menggunakan password dalam bentuk plaintext maka kemungkinan besar akan terjadi sniffing pada web anda.

![bug 10](https://user-images.githubusercontent.com/53895082/66939026-79140480-f06c-11e9-8238-1fe1d092d9c4.png)

**Comment by MadeBy-Ali** [comment]
![image](https://user-images.githubusercontent.com/49668571/67652370-2c3b0280-f977-11e9-9a0a-87df8d54ed5d.png)

done, sekarang password yang di register tidak lagi berbentuk plain text
