### ISSUE TITLE
Pesanan tidak bisa di click

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#11]
Menu "pesanan" tidak bisa di click. Seharusnya bagian seperti ini yang menjadi fokus utama karena berada pada navbar (utama).

![Screen Shot 2019-10-17 at 7 24 51 PM](https://user-images.githubusercontent.com/53895082/67008585-02324680-f114-11e9-84d3-1d89465e1ca2.png)

**Comment by belladewusa** [comment]
![Screenshot (114)](https://user-images.githubusercontent.com/55181780/67279727-cb827480-f4f5-11e9-9a51-fc99ec13ec8a.png)
