### ISSUE TITLE
Check box yang tidak perlu di centang

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#12]
Pada menu signup terdapat check box yang menyatakan setuju pada seluruh syarat. Ternyata, walaupun tombol tersebut tidak di tekan seorang user masih bisa tetap mendaftar.

![Screen Shot 2019-10-17 at 7 27 38 PM](https://user-images.githubusercontent.com/53895082/67008801-7ff65200-f114-11e9-8625-59e3e500e308.png)

**Comment by MadeBy-Ali** [comment]
![messageImage_1571754387479](https://user-images.githubusercontent.com/49668571/67296457-aea86a00-f512-11e9-8a4f-fc83231c7aae.jpg)

done, register button tidak bisa di click kalau input box belum di checklist
