### ISSUE TITLE
Tulisan term of service tidak ada isinya

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#13]
Seharusnya ketika term of service di tekan maka akan memunculkan aturan-aturan yang harus di sanggupi oleh orang yang akan mendaftar.

![Screen Shot 2019-10-17 at 7 30 46 PM](https://user-images.githubusercontent.com/53895082/67009509-fc3d6500-f115-11e9-9624-a882bf06856f.png)

**Comment by MadeBy-Ali** [comment]
![1571739098882](https://user-images.githubusercontent.com/49668571/67276612-47c58980-f4ef-11e9-96e6-8687a65e9c62.jpg)

done
