### ISSUE TITLE
Login with yang tidak ada link nya

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#14]
pada halaman login.html terdapat 3 logo untuk login namun semua tidak bisa di tekan dan tidak memunculkan suatu pop up page untuk login.

![Screen Shot 2019-10-17 at 7 43 02 PM](https://user-images.githubusercontent.com/53895082/67009770-88e82300-f116-11e9-95d7-2b7f7df657cb.png)

**Comment by MadeBy-Ali** [comment]
![socmed](https://user-images.githubusercontent.com/49668571/67277353-d090f500-f4f0-11e9-9e46-e7f5d40e167e.jpg)

Tiap social media button sudah terbubung ke login website yang sesuai
