### ISSUE TITLE
Jumlah pesanan yang bisa minus (-)

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#15]
Seharusnya sih pesanan selalu positif namun kali ini yang di input bisa minus.

![Screen Shot 2019-10-17 at 7 50 38 PM](https://user-images.githubusercontent.com/53895082/67010579-1e37e700-f118-11e9-98a0-fdc6bca7ac3b.png)

**Comment by MadeBy-Ali** [comment]
![messageImage_1571754230423](https://user-images.githubusercontent.com/49668571/67296161-478ab580-f512-11e9-84cb-cfb452e46363.jpg)

done, input minimal dibuat jadi "1"
