### ISSUE TITLE
Page cart yang tidak ada 

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#16]
Setelah mengajukan pesanan lalu tidak ditemukan cart.html

![Screen Shot 2019-10-17 at 7 56 48 PM](https://user-images.githubusercontent.com/53895082/67010713-60612880-f118-11e9-9cdb-dfdc393e4a79.png)

**Comment by Senivri** [comment]
![Screenshot 2019-10-22 17 54 18](https://user-images.githubusercontent.com/55181810/67279399-1b147080-f4f5-11e9-8488-3d9b57952a7d.png)
![Screenshot 2019-10-22 17 54 25](https://user-images.githubusercontent.com/55181810/67279411-21a2e800-f4f5-11e9-98b1-36519659a2fa.png)
