### ISSUE TITLE
Link yang tidak ada juga

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#17]
Link nya tidak ditemukan lagi dan hanya melakukan refresh page saja.

![Screen Shot 2019-10-17 at 7 58 58 PM](https://user-images.githubusercontent.com/53895082/67010845-aae2a500-f118-11e9-8457-f6d3909683f0.png)

**Comment by belladewusa** [comment]
![Screenshot (115)](https://user-images.githubusercontent.com/55181780/67279770-e359f880-f4f5-11e9-9174-67d530fa2994.png)
