### ISSUE TITLE
tombol pesan sekarang dan cek model tidak berfungsi

### ISSUE THREAD

**Issue by hanaghaliyah** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#19]

**Comment by belladewusa** [comment]
![Screenshot (116)](https://user-images.githubusercontent.com/55181780/67279920-392ea080-f4f6-11e9-84b2-e32f00b7599a.png)
![Screenshot (119)](https://user-images.githubusercontent.com/55181780/67279924-3b90fa80-f4f6-11e9-8cd0-7ff671d35b16.png)
