### ISSUE TITLE
Css terpotong

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#2]
Masih pada file index.html ada css yang terpotong karena jarak margin dengan bagian atas terlalu jauh. Sudah saya buka di 3 web dengan hasil yang sama

![bug 2 brave](https://user-images.githubusercontent.com/53895082/66937042-f2a9f380-f068-11e9-9b5a-0b9babe683e3.png)
![bug 2 edge](https://user-images.githubusercontent.com/53895082/66937043-f2a9f380-f068-11e9-8326-a203b37abb3f.png)
![bug 2](https://user-images.githubusercontent.com/53895082/66937044-f3428a00-f068-11e9-9774-b9c5d6733701.png)

**Comment by belladewusa** [comment]
![Screenshot (111)](https://user-images.githubusercontent.com/55181780/67279312-ef918600-f4f4-11e9-9ad2-08ec90b1a166.png)
