### ISSUE TITLE
Tidak ada perubahan sebelum maupun sesudah login pada website 

### ISSUE THREAD

**Issue by indrawidnyana** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#21]
Tidak ada perubahan sebelum maupun sesudah login pada website ( tampilan masih sama yang dimana berisi login dan register padahal telah register dan login sebelumnya )
![eldorado1](https://user-images.githubusercontent.com/54881761/67173362-af44e180-f3e8-11e9-8f81-0465b49830f2.png)

**Comment by MadeBy-Ali** [comment]
![messageImage_1571756255474](https://user-images.githubusercontent.com/49668571/67299671-2d070b00-f517-11e9-83c1-d843ce9d2cd7.jpg)

done
