### ISSUE TITLE
Tampilan search pada masing-masing tempat fitur berbeda tulisan

### ISSUE THREAD

**Issue by indrawidnyana** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#22]
masih ada perbedaan tulisan pada fitur search. seperti contohnya di tulisan beranda dan tulisan kontak , fitur search ada yang menggunakan bahasa indonesia dan inggris
![eldorado2 1](https://user-images.githubusercontent.com/54881761/67173637-8a9d3980-f3e9-11e9-9a8d-f76c0927b9b8.png)
![eldorado2 2](https://user-images.githubusercontent.com/54881761/67173640-8a9d3980-f3e9-11e9-8fc9-58611a14e6e9.png)

**Comment by belladewusa** [comment]
![Screenshot (120)](https://user-images.githubusercontent.com/55181780/67279976-55cad880-f4f6-11e9-98c5-2660eb3e9651.png)
