### ISSUE TITLE
tidak ada error message?

### ISSUE THREAD

**Issue by nashirat** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#23]
![image](https://user-images.githubusercontent.com/55182333/67180149-e2946a00-f402-11e9-859b-fdf86bde70ba.png)

**Comment by MadeBy-Ali** [comment]
![1571739385627](https://user-images.githubusercontent.com/49668571/67276919-e18d3680-f4ef-11e9-975b-8329334acc73.jpg)

done
