### ISSUE TITLE
Image error

### ISSUE THREAD

**Issue by nashirat** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#24]
![image](https://user-images.githubusercontent.com/55182333/67180213-1cfe0700-f403-11e9-9dc0-231b9e291ac1.png)

**Comment by Senivri** [comment]
![10779427863932](https://user-images.githubusercontent.com/55181810/67196862-cf46c600-f425-11e9-998a-3f232e3cbe02.jpg)
