### ISSUE TITLE
login gagal

### ISSUE THREAD

**Issue by peacefulhack** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#25]
login gagal request not found!
![image](https://user-images.githubusercontent.com/49645946/67190594-6b6ad000-f41a-11e9-96e0-c22f91520869.png)

**Comment by MadeBy-Ali** [comment]
![1571739385627](https://user-images.githubusercontent.com/49668571/67276892-cae6df80-f4ef-11e9-9162-bcd71169072d.jpg)

done
