### ISSUE TITLE
berlangganan harus di kasih controller a@b.c

### ISSUE THREAD

**Issue by peacefulhack** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#26]
![image](https://user-images.githubusercontent.com/49645946/67190745-b84ea680-f41a-11e9-9220-86bd370fe4c6.png)

**Comment by MadeBy-Ali** [comment]
![messageImage_1571753947448](https://user-images.githubusercontent.com/49668571/67296272-6ee18280-f512-11e9-82d0-1a0ee2c24f3a.jpg)

done
