### ISSUE TITLE
Gambar yang tidak tampil

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#3]
Masih pada index.html ada gambar yang tidak tampil. Sudah di cek di 3 browser sekaligus.

![bug 3](https://user-images.githubusercontent.com/53895082/66937175-3270db00-f069-11e9-9356-3433c8a5e379.png)

**Comment by Senivri** [comment]
![10779427863932](https://user-images.githubusercontent.com/55181810/67196692-7ecf6880-f425-11e9-8e55-d109ae747182.jpg)
