### ISSUE TITLE
Subscribe yang bisa di isi asal

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#4]
pada halaman contact.html bagian bawah tempat subscribe masih bisa di isi dengan huruf acak (dimana seharusnya untuk subscribe harus menggunakan email) 

![bug 4](https://user-images.githubusercontent.com/53895082/66937448-aad79c00-f069-11e9-8b4e-a0e2b6c9c471.png)

**Comment by irsyadali1** [comment]
![messageImage_1571753947448](https://user-images.githubusercontent.com/49668571/67295925-fd093900-f511-11e9-82c5-88bd618a290e.jpg)

done

**Comment by MadeBy-Ali** [comment]
![messageImage_1571753947448](https://user-images.githubusercontent.com/49668571/67295985-0db9af00-f512-11e9-9b17-38e66a9e3daa.jpg)

done
