### ISSUE TITLE
Menu yang tidak bisa di click

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#5]
Pada halaman index.html pada bagian beranda terdapat menu yang tidak bisa di click antara lain ( mulai menjahit, fitting, promo, mulai menjahit, menu three)

![bug 5](https://user-images.githubusercontent.com/53895082/66937695-23d6f380-f06a-11e9-9186-616fcde56b8c.png)

**Comment by belladewusa** [comment]
![Screenshot (112)](https://user-images.githubusercontent.com/55181780/67279589-80686180-f4f5-11e9-9379-ebec677e1f6a.png)
