### ISSUE TITLE
Tidak dapat sort menu

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#6]
pada halaman shop.html terdapat 2 sort menu, menu spesialis toko dan daerah yang mana walaupun sudah di sort dan di select namun tidak menghasilkan sesuatu yang berbeda. 

![bug 6](https://user-images.githubusercontent.com/53895082/66937931-7b755f00-f06a-11e9-913b-3e86295e9793.png)

**Comment by Senivri** [comment]
![Screenshot 2019-10-22 17 50 46](https://user-images.githubusercontent.com/55181810/67279074-7f830000-f4f4-11e9-8c95-3d8814ac176b.png)
