### ISSUE TITLE
Link yang salah

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#7]
pada halaman shop.html bagian bawah terdapat link "Copyright ©2019 Kampuh | Indonesia Oleh El Dorado Team" yang mana bila El Dorado Team di click maka akan menuju ke web https://colorlib.com/ 

![bug 7 href](https://user-images.githubusercontent.com/53895082/66938127-d60ebb00-f06a-11e9-8072-e77c64a10ced.png)
![Uploading bug 7.png…]()

**Comment by Senivri** [comment]
![Screenshot 2019-10-22 17 51 57](https://user-images.githubusercontent.com/55181810/67279165-a93c2700-f4f4-11e9-9a0d-2f064354ac8c.png)
![Screenshot 2019-10-22 17 52 01](https://user-images.githubusercontent.com/55181810/67279175-accfae00-f4f4-11e9-8e4c-76fb39974992.png)
