### ISSUE TITLE
Tombol informasi yang tidak bisa menampilkan informasi

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#8]
Pada halaman shop.html bagian bawah terdapat 9 menu untuk mendapatkan informasi lain nya dari website El Dorado Team namun tidak bisa link kemana-mana dan hanya mengembalikan ke bagian atas dari halaman shop.html 

![bug 8](https://user-images.githubusercontent.com/53895082/66938523-867cbf00-f06b-11e9-9dfb-a787faa8c493.png)

**Comment by belladewusa** [comment]
![Screenshot (113)](https://user-images.githubusercontent.com/55181780/67279686-b6a5e100-f4f5-11e9-882b-34ac65e1e5b9.png)
