### ISSUE TITLE
Tombol yang salah link

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-el-dorado#9]
Pada menu beranda di halaman index.html pada saat di click "Login" seharusnya berpindah ke login.html namun malah menampilkan register.html

![bug 9](https://user-images.githubusercontent.com/53895082/66938820-17539a80-f06c-11e9-97dc-d552862be256.png)

**Comment by Senivri** [comment]
![Screenshot 2019-10-22 17 53 08](https://user-images.githubusercontent.com/55181810/67279249-d092f400-f4f4-11e9-8ceb-6b8a2c73ead5.png)
